version: '3.2'

services:
    db:
        image: mariadb:10.5
        container_name: mariaDB
        ports:
         - '3306:3306'
        environment:
         - 'MYSQL_ROOT_PASSWORD=123456'
    app:
        depends_on:
        - db
        image: phpmyadmin
        ports:
         - '8888:80'
        environment:
         - 'PMA_HOST:db'
         - 'MYSQL_ROOT_PASSWORD=123456'